version: '3.8'

services:
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8081:80
    depends_on:
      - app-backend
    container_name: portfolio--email-server-nginx
  
  app-backend:
    image: portfolio-email-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:3001
    # secrets:
    #   - my_secret
    # env_file: 
    #   - ./server/.env
    # volumes:
    #   - ./server/:/usr/src/app
    #   - /usr/src/app/node_modules
    container_name: portfolio-email-server

  # redis:
  #   image: redis
  #   ports:
  #     - 6379:6379
  #   command: ['redis-server', '--appendonly', 'yes']
  #   volumes:
  #     - ./portfolio-email-server/redis_data:/data
  #   container_name: todo-redis-dev